title: Dr.Gestão
description: Manual do Usuário
theme: jekyll-theme-leap-day
show_downloads: false
github:
  is_project_page: false

# Configurações do site
lang: pt-BR
timezone: America/Sao_Paulo

# URLs
url: "https://marcostaira.github.io"
baseurl: "/DrGestao"

# Navegação
navigation:
  - title: Home
    url: /
  - title: Agenda
    url: /Agenda
  - title: Pacientes
    url: /Pacientes
  - title: FAQ
    url: /FAQ
